### ISSUE TITLE
Minimal specifications / support for Debian 8?

### ISSUE THREAD

**Issue by Macleykun** [Taknok/NadekoBot#2]
I'm looking to get NadekoBot working on a VPS. But ik i'm running into some memory problems.

I want to know if with your GitHub it's possible to boot with around 240 MB memory and one vcpu.

Also would this project be able to run just fine on Debian 8?

I'm kinda new to all this so i rather ask then fuck things up / find out it's not even possible.

**Comment by Taknok** [comment]
240MB seems to be a little low, even the raspberry have 1GB. You still can try, maybe with a swap it could work, but it will be very slow. Just to use the c# runtime 240MB maybe not enouth [(link).](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements) It could be why you have memory issues. For the vcpu it shouldn't trigger any problems I think.
The project is tested on raspbian, which is based on debian so yes it should work. You have to check you architecture, if it's an arm (like rapsberry) this project is ok, else go to the Kwoth project.

Click [here](https://superuser.com/a/106545/756412) to check your architecture.

It's by trying that we learn :) and I'm interested if you manage to make it work. If you have any others questions do not hesitates.

**Comment by Macleykun** [comment]
True about the fact that with trying we learn. I'm still trying to push it with 300mb. Maybe if i then lower it back to 256 it could work.

I honestly were just checking if your project was so modified that it would use less memory or smth. Because what i know of a PI is that it's a small little thing that doesn't have that much specs.

I'm gonna look if i can ask my provider to make a swap disk partition or smth to drop some memory stuff away. Thanks alot for the help! I'm sure 240 isn't gonna do it but with a bit of swp it should work! I'll update you on it if i ever get it to work.

**Comment by Taknok** [comment]
No I didn't modify for the ram adjustment for the moment. I'm quite busy and maybe next step will be to fix the pipe issue with the music module. After improve ram optimization.

It's strange to have only 240MB... I hope it's free :)

So to answer to the title, the minimum specifications are the ones for the dotnet core framework.

**Comment by Macleykun** [comment]
Aah ic thanks buddy! And yes it's free! If you google SkySilk you find a free VPS provider that gives root access and unlimited bandwith. Bin using it to run Nadeko - FredBoat and Discord.RSS and a selfbot. It's all running smooth because no charges are applied because they are in beta.

I know that this solution isn't permanent so i'm looking to still get all those things for free in the 'cloud'. It's only NadekoBot that's having an issue with memory and the Heroku port being dead.

I hope the music module isn't going to be much trouble for you! Wish you lots of lucks with this cool project! You should ask Kwoth to get the Contributers role! You deserve it way more then Kuro atm!

**Comment by Taknok** [comment]
Ok thank, I will give a look to it, free stuffs are always cool.

Thank you, I hope too ^^. Thanks again. Haha, I cannot judge this and that's not what it matter for me, I just what to solve/create when I have an idea or like an idea and nothing exist atm.

**Comment by Macleykun** [comment]
So, after a year of me being silent xD, i think the following specs are needed for NadekoBot:
When uncompiled, you would need more then 512MB and 1 core. Will take some time but it will succeed.

I do believe that if you have it pre-compiled, you would save alot in the memory department (assuming you don't use music, the memory leak is still a thing i think :P. I assume you could do it with even 256MB if you do it that way.

@Taknok feel free to close the issue with these insights :P

**Comment by Taknok** [comment]
Thank you for your return ! XD
