### ISSUE TITLE
publish folder missing

### ISSUE THREAD

**Issue by chnjn** [Taknok/NadekoBot#3]
I've followed instructions here as closely as I can, however upon inputting the command "dotnet publish -r ubuntu.16.04-arm -c Release" only up till /bin/Release/netcoreapp2.0/ubuntu.16.04-arm/ is created, I've tried creating the folder, then creating the creds.json file then following the rest of the instructions, but got stuck at "./NadekoBot, 1st boot can take 2min. You can use tmux for background run : guide." need clarification on this, thank you! Sorry quite new to this,

**Comment by Taknok** [comment]
I don't understand where you are blocked/where is the imprecision. Did you solve it ? Where can I add more information ? I want to be the more clear for everyone so do no hesitate.

 1. Normally `dotnet publish -r ubuntu.16.04-arm -c Release` creates all folders needed if there aren't there...
2. If this is about the `./NadekoBot` this is the shell command that tell to linux to run the binary/ execution file NadekoBot.
3. Is it about `tmux` ? Linux have a father - son process organization (not really anymore but forget), so all programs started are the son of another process, except for the father of all :  [the init process](https://en.wikipedia.org/wiki/Init). When you kill a father, all sons the will be killed or became zombies too (So never kill process 1, the init (but that isn't true anymore... forget too, just don't kill it :) )). So when you start your **NadekoBot** in the shell, your **Nakeko** process is the son of shell and when you close the shell, you kill your Nadeko. To avoid that you can switch the father of your process, by using `tmux` for example. Kwoth have created a guide to use it, so I linked it.

**Comment by chnjn** [comment]
Yes I've managed to solve it, since I've downloaded the installer dotnet sdk cli 2.1.0 for x86 at first, not realizing that it gave me a few errors until I've installed the x64 vers, and then running the commands again gave me the folders required. That was where I went wrong. So far it has been working well, thank you for your hardwork Taknok :)

**Comment by Taknok** [comment]
Ok, I'm glad you solved your the issue !
You are welcome :)
