### ISSUE TITLE
[Query] Raspberry Pi Performance

### ISSUE THREAD

**Issue by DelKatey** [Taknok/NadekoBot#4]
Hi,

Sorry for using the issue system to ask this question, but how much CPU does Nadeko Bot typically use up, when using your instructions to install it on Raspbian (Jessie)?

Katie.

**Comment by Taknok** [comment]
Hi,

No problem at all. This is depending of the state of the bot. At boot it's 100%. In waiting mode (without cmd) it's around 0.3% and if you run a cmd usually 50% just during the time of the command execution, the higher I've seen is 70%. This results on Raspbian Jessie with a Raspberry Pi 3 B+.
I hope that help you. Do not hesitates if you have more questions :)
As said in #2 optimization will come later, I'm focus on music when I have time for the moment.

**Comment by DelKatey** [comment]
I see, thanks for the information :)

I guess I will wait until after that phase then, as having Nadeko alone take up up to 70% might cause issues with the other 4 to 5 bots on my Pi (3B) atm >.<

**Comment by Taknok** [comment]
Yep Nadeko is quite an heavy bot atm :/
