### ISSUE TITLE
[Query]

### ISSUE THREAD

**Issue by chnjn** [Taknok/NadekoBot#5]
Sorry to interrupt your work on the music command, but any updates on updating the current version to the newer version that Kwoth has pushed out? Or if there's anyway to self update?

**Comment by Taknok** [comment]
I will take a look to the new version, and I will try to publish a 'self conversion' guide for later update for people who wants it asap :)

**Comment by Taknok** [comment]
So I updated this repo. Basically this time a simple merge did the trick. To keep your data backup `data/` and then copy it again in `publish`.

**Comment by chnjn** [comment]
Sweet! thanks for the update!
