### ISSUE TITLE
publish folder is empty, dotnet commands aren't working, raspberry pi

### ISSUE THREAD

**Issue by lxtrem** [Taknok/NadekoBot#6]
Helloh, here is my issue :
## Expected Behavior
The possible utilisation of dotnet etc...

## Actual Behavior
`bash: dotnet: command not found`

## Steps to Reproduce the Problem
i have just follow the installation :
`sudo apt update`
`sudo apt upgrade`
`sudo apt install libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip`
succeed but the others commands can't be execute...

## Specifications

  - Version: Debian 9.1
  - Platform: RaspberryPi
  - Subsystem:

thanks

**Comment by Taknok** [comment]
Hi,

Sorry I was quite busy the past days. You are trying to run the `dotnet` command on the raspberry ? or on the window ?

**Comment by lxtrem** [comment]
Hello,
Don' worry, i am not in a hurry.
I am trying to run the dotnet commands on my RPI

**Comment by Taknok** [comment]
Actually this project isn't running dotnet command on RPI. This is a cross compile from Windows to rasp. At the end you just have to launch the executable `./NadekoBot`. I don't know if you want to run dotnet command on rasp for another project or not. 
If you want to run on another project, maybe take a look to [this](https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/) (maybe you already did). I didn't tried it, and it is specified that their isn't any sdk for dotnet on rasp for the moment. 
If it's for Nadeko their is no need for the moment.

Do not hesitate to precise or ask more questions :)

**Comment by lxtrem** [comment]
Ok, thanks, but without the dotnet commands, i can't install NadekoBot on my RPI

**Comment by Taknok** [comment]
You can. That is the point of the cross compiling. When you run `dotnet run` there is actually a sort of code compilation (not exactly see [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore2x)).
In this project we cross compile, that mean that your window will produce code that the raspberry will understand, and the windows will not. Then you transfer this code on the raspberry and run it like a normal program. In the Readme it's precised which platform what you have to do.

**Comment by lxtrem** [comment]
Ok, sorry, i didn't undurstand, but i have another issue : when i run `dotnet restore`, i have this :
`MSBUILD : error MSB1003: Spécifiez un fichier projet ou solution. Le répertoire de travail actif n'en contient aucun.`
That is meaing "Specify a project or a solution. The current directory don't contain any" (approximately)

**Comment by Taknok** [comment]
In which folder are you when starting the compilation ? You have to be in the project folder `Nadekobot`

---

French ? Dans quel dossier es tu au lancement de la compilation ? Tu dois etre dans le dossier du projet `Nadekobot`

**Comment by lxtrem** [comment]
Ok, thanks.
I am french but i understand english.
Now i am a this step :
`Copy credential.json in ./bin/Release/netcoreapp2.0/ubuntu.16.04-arm/publish.`
but i don't have the directory /bin/Release

**Comment by Taknok** [comment]
Ok, maybe in `src/NadekoBot/bin/Release/netcoreapp2.0/ubuntu...` ?

**Comment by lxtrem** [comment]
No, but i am on debian and i didn't still install NadekoBot on my RPI, so it can't be that

**Comment by Taknok** [comment]
Ok, you have a raspberry with a raspbian installed on it AND a computer with a debian, is that right ?

**Comment by lxtrem** [comment]
I have a raspberry with raspbian and a computer with Windows ( 👎 )

**Comment by Taknok** [comment]
Ok. So you ran `dotnet publish -r ubuntu.16.04-arm -c Release` successfully and past you `credential.json` in the publish folder ? both operations on your windows

**Comment by lxtrem** [comment]
i ran `dotnet publish -r ubuntu.16.04-arm -c Release` on Windows successfully and i past my credential.json on windows

**Comment by Taknok** [comment]
Ok perfect so transfer you publish folder from windows to raspberry. Then open a terminal on the raspberry, go into the publish folder. Change the authorization with `chmod` and then launch the bot with `./NadekoBot`

**Comment by lxtrem** [comment]
I don't know if we are speaking about the same publish folder...

**Comment by Taknok** [comment]
Do you have multiple publish folders ?

**Comment by lxtrem** [comment]
on windows ?

**Comment by Taknok** [comment]
On windows you have the folder named "publish" located at `NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/ubuntu16...` in this folder you create/copy/paste the `credential.json` with everything asked by Kwoth (link how to create is in readme). Then you transfer this folder where you just copy your `credential.json` from windows to the rapsberry (you said you can in `/home/pi/Public` of the raspberry)

**Comment by lxtrem** [comment]
Ok that's works !
Thanks very much !

**Comment by Taknok** [comment]
You are welcome.
