### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by 4maself** [Taknok/NadekoBot#9]
Hey,
I'm having trouble with compiling the current code. Any idea what could be the problem? 
## Expected Behavior
Succesfull compilation

## Actual Behavior
![57fc23b75388e450b097a6b475acfeef](https://user-images.githubusercontent.com/24295086/40232021-7d0d65d8-5a9d-11e8-9857-bde2b7af1683.png)

## Steps to Reproduce the Problem

  1. Download the repo
  2. Download dotnet SDK
  3. Open powershell in the repo folder 
  4. dotnet restore 
  5. dotnet publish -r ubuntu.16.04-arm -c Release

## Specifications

  - Dotnet version: 2.1.200 x64
  - Platform: Windows 10 (1803)

**Comment by Taknok** [comment]
Are you using the sources from this repository ? I tested on a fresh install and the code from this repo is working :/

![capture](https://user-images.githubusercontent.com/12498020/40235882-e8e40f88-5aab-11e8-9c0e-84cf4508b826.JPG)

**Comment by 4maself** [comment]
I am, yes. Even tried the 1.9 version from Kwoth. It compiled, but was useless on the Pi. I will try it on my laptop. Maybe it makes any difference, since my pc is running an AMD processor.

**Comment by 4maself** [comment]
Getting the same error on my laptop, unfortunately :|

**Comment by Taknok** [comment]
Try to clean the package downloaded by dotnet to do a clean install again.

**Comment by 4maself** [comment]
I tried  `dotnet clean` if that's what you meant, but I got the same errors after `dotnet restore` and `dotnet publish -r ubuntu.16.04-arm -c Release`

**Comment by Taknok** [comment]
Did you tried first with the repository of kwoth ? Or mine ?

When you run `dotnet restore` packages are downloaded locally. If you tried Kwoth repo 1st, there may be conflic version for my repo. The code on this repo is quite old (but working). The new code of Kwoth ask a lot of cpu, which rasp hasn't. I have to work on it, but I haven't time for it recently.
Search a hidden folder .dotnet or so which should has this packages. Or try a fresh install on a VM.

**Comment by 4maself** [comment]
I tried your repo first. I found the .dotnet folder in my user folder, but after deleting the content the problem still persists. I'm going to try a fresh Win10 in VMWare. Hope that helps.
I'm already glad that you're putting time into helping me.

**Comment by 4maself** [comment]
I just tried it on a freshly downloaded VM and It still errors :/

**Comment by 4maself** [comment]
I also asked some friends to try compile it, but they had the same issues.

**Comment by Taknok** [comment]
I will take a closer look tomorrow :/

**Comment by 4maself** [comment]
Oh before i forget. Your screenshot just shows the restore process but not the cross-compiling part. It's there where it starts to error.

**Comment by Taknok** [comment]
I compiled a version, but I have lost my SD card adapter... If you want you can try my compiled version : https://www12.zippyshare.com/v/HVAjgnoT/file.html
⚠️ You still need to install dependencies on rasp and create the credentials file !

You can try to solve the warnings, maybe it will fix the error messages. I suggest you to edit `NadekoBot\src\NadekoBot\NadekoBot.csproj` and replace `<PackageReference Include="Discord.Net" Version="2.0.0-alpha-build-00824" />` by `<PackageReference Include="Discord.Net" Version="1.0.2" />`

**Comment by 4maself** [comment]
Your compiled version worked like a charm, thanks!

I also changed the Discord.Net version to 1.0.2 and that worked aswell. Thanks for your time man!
